name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths-ignore:
      - ".git**"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  lint-ruby:
    name: Lint Ruby
    uses: publishing-platform/publishing-platform-infrastructure/.github/workflows/rubocop.yml@main

  test-ruby:
    name: Test Ruby
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run RSpec
        run: bundle exec rspec
