name: "Merge Dependabot PRs"

on:
  schedule:
    # 8:30am UTC, Mon-Fri.
    - cron: '30 8 * * 1-5'
  workflow_dispatch: {}

jobs:
  merge-dependabot-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup ruby
        uses: ruby/setup-ruby@0dafeac902942906541bc140009cdbf32665b601 # v1.315.0
        with:
          bundler-cache: true

      - name: Run Dependabot-merger script
        env:
          AUTO_MERGE_TOKEN: ${{ secrets.AUTO_MERGE_TOKEN }}
        run: |
          bundle exec ruby bin/merge_dependabot_prs.rb