name: "Merge Dependabot PRs"

on:
  schedule:
    # 8:30am UTC, Mon-Fri.
    - cron: '30 8 * * 1-5'
  workflow_dispatch: {}

jobs:
  merge-dependabot-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup ruby
        uses: ruby/setup-ruby@7372622e62b60b3cb750dcd2b9e32c247ffec26a # v1.302.0
        with:
          bundler-cache: true

      - name: Run Dependabot-merger script
        env:
          AUTO_MERGE_TOKEN: ${{ secrets.AUTO_MERGE_TOKEN }}
        run: |
          bundle exec ruby bin/merge_dependabot_prs.rb